/**
 * UWF Skill Scaffolder
 *
 * Generates a new persona skill skeleton from a simple config.
 *
 * Usage:
 *   node .github/skills/scaffold-skill.mjs --name <skill-name> --stages "stage1,stage2,stage3"
 *
 * Example:
 *   node .github/skills/scaffold-skill.mjs --name qa_lead --stages "test-planning,coverage-review,sign-off"
 *
 * Produces:
 *   .github/skills/uwf-<name>/run.mjs     — gate enforcement script with TODO stubs
 *   .github/skills/uwf-<name>/SKILL.md    — minimal persona skill doc
 */

import fs from "node:fs";
import path from "node:path";

// ---------------------------------------------------------------------------
// CLI parsing
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const name = argValue(args, "--name");
const stagesRaw = argValue(args, "--stages");

if (!name || !stagesRaw) {
  process.stderr.write(
    "Usage: node scaffold-skill.mjs --name <skill-name> --stages \"stage1,stage2,...\"\n"
  );
  process.exit(2);
}

const stages = stagesRaw.split(",").map((s) => s.trim()).filter(Boolean);
const skillDir = path.join(process.cwd(), ".github", "skills", `uwf-${name}`);

if (fs.existsSync(skillDir)) {
  process.stderr.write(`Skill directory already exists: ${skillDir}\nAborting to avoid overwrite.\n`);
  process.exit(1);
}

fs.mkdirSync(skillDir, { recursive: true });

// ---------------------------------------------------------------------------
// Generate run.mjs
// ---------------------------------------------------------------------------

const stageBlocks = stages.map((stage) => {
  return `  {
    name: "${stage}",
    agent: "uwf-${name}-${stage}",  // TODO: verify agent name
    maxRetries: 2,
    onGateFailure: "retry",
    gate(outputPath, statePath) {
      const failures = [];
      // TODO: add artifact checks for this stage, e.g.:
      // const f1 = requireNonEmptyFile(path.join(outputPath, "${name}-${stage}.md"), "${name}-${stage}.md");
      // if (f1) failures.push(f1);
      return failures.length ? gateFail("${stage}", failures) : gatePass("${stage}");
    },
  }`;
}).join(",\n\n");

const runMjs = `/**
 * UWF ${name} persona — gate enforcement script.
 *
 * Usage (called by the orchestrator agent via terminal):
 *   node .github/skills/uwf-${name}/run.mjs --list-stages
 *   node .github/skills/uwf-${name}/run.mjs --check-gate <stageName> [--output-path <path>] [--state-path <path>]
 *
 * Exit codes:  0 = gate passed   1 = gate failed   2 = usage error
 *
 * Generated by scaffold-skill.mjs — fill in the TODO stubs before use.
 */

import path from "node:path";
import fs from "node:fs";
import {
  runCLI,
  gatePass,
  gateFail,
  requireNonEmptyFile,
  requireFileContains,
  requireFilesWithPrefix,
  requireFileMatchingPattern,
} from "../uwf-orchestration-engine/skill-runner.mjs";

const stages = [
${stageBlocks},
];

runCLI(stages);
`;

fs.writeFileSync(path.join(skillDir, "run.mjs"), runMjs);

// ---------------------------------------------------------------------------
// Generate SKILL.md
// ---------------------------------------------------------------------------

const stageTableRows = stages
  .map((stage, i) => `| ${i + 1} | \`${stage}\` | \`uwf-${name}-${stage}\` | TODO: describe purpose |`)
  .join("\n");

const rosterRows = stages
  .map((stage) => `| \`uwf-${name}-${stage}\` | TODO: describe role |`)
  .join("\n");

const skillMd = `\`\`\`skill
# Skill: uwf-${name}

TODO: one-line description of this persona.

---

## Persona Configuration

| Property | Value |
|---|---|
| \`workflow\` | \`${name}\` |
| \`mode\` | \`TODO\` |
| Artifact prefix | \`${name}-\` |
| Output path default | \`./tmp/workflow-artifacts\` |

---

## Subagent Roster

| Subagent | Role |
|---|---|
${rosterRows}

---

## Stage Sequence

Gate enforcement is implemented in \`run.mjs\` — see the gate() function for each stage.
Fill in the TODO stubs in run.mjs before running this skill.

| # | Stage | Subagent | Purpose |
|---|---|---|---|
${stageTableRows}

---

## Persona-Specific Operating Rules

- TODO: add any persona-specific rules here.

\`\`\`
`;

fs.writeFileSync(path.join(skillDir, "SKILL.md"), skillMd);

// ---------------------------------------------------------------------------
// Done
// ---------------------------------------------------------------------------

console.log(`\nScaffolded new skill: uwf-${name}`);
console.log(`  ${path.relative(process.cwd(), path.join(skillDir, "run.mjs"))}`);
console.log(`  ${path.relative(process.cwd(), path.join(skillDir, "SKILL.md"))}`);
console.log(`\nNext steps:`);
console.log(`  1. Fill in the gate() TODO stubs in run.mjs`);
console.log(`  2. Add agent files: .github/agents/uwf-${name}-<stage>.agent.md for each stage`);
console.log(`  3. Register agents in uwf-core-orchestrator.agent.md`);
console.log(`  4. Bootstrap: uwf-core-orchestrator workflow=${name}`);

// ---------------------------------------------------------------------------
// CLI helper
// ---------------------------------------------------------------------------
function argValue(args, flag) {
  const idx = args.indexOf(flag);
  return idx !== -1 ? args[idx + 1] : undefined;
}
